/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat.modelli;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 *
 * @author Andrea
 */
public class NuovaChat extends javax.swing.JDialog {
    int codutente1,codutente2;
    String username,risultato;
    Socket sock;
    BufferedReader input;
    PrintWriter output;
    DocumentBuilderFactory dbf=DocumentBuilderFactory.newInstance();
    DocumentBuilder db;
    Document d;
    TransformerFactory transformerFactory=TransformerFactory.newInstance();
    Transformer transformer;
    DOMSource source;
    StreamResult result;
    Element root,tipo,codu1,nomut; 
    /**
     * Creates new form NuovaChat
     * @param parent
     * @param modal
     * @param codutente
     * @param sock
     * @throws java.io.IOException
     */
    public NuovaChat(java.awt.Frame parent, boolean modal,int codutente,Socket sock) throws IOException {
        super(parent, modal);
        initComponents();
        //codice utente creatore
        this.codutente1=codutente;
        this.sock=sock;
        input=new BufferedReader(new InputStreamReader(this.sock.getInputStream()));
        output=new PrintWriter(this.sock.getOutputStream(),true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeutente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        testo = new javax.swing.JTextArea();
        Invia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("nuova chat");
        setPreferredSize(new java.awt.Dimension(290, 160));
        setResizable(false);
        setSize(new java.awt.Dimension(290, 160));

        nomeutente.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        testo.setEditable(false);
        testo.setColumns(20);
        testo.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        testo.setLineWrap(true);
        testo.setRows(5);
        testo.setText("inserire l'username dell'utente con cui iniziare una nuova chat:");
        testo.setWrapStyleWord(true);
        jScrollPane1.setViewportView(testo);

        Invia.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        Invia.setText("invia");
        Invia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeutente)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Invia))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeutente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Invia))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InviaActionPerformed
        try {
            username=nomeutente.getText();
            //creazione file xml
            db=dbf.newDocumentBuilder();
            transformer=transformerFactory.newTransformer();
            d=db.newDocument();
            root=d.createElement("richiesta");
            d.appendChild(root);
            
            tipo=d.createElement("tipo");
            tipo.appendChild(d.createTextNode("nuova_chat"));
            root.appendChild(tipo);
            
            codu1=d.createElement("codu1");
            codu1.appendChild(d.createTextNode(Integer.toString(codutente1)));
            root.appendChild(codu1);
            
            nomut=d.createElement("nome_utente");
            nomut.appendChild(d.createTextNode(username));
            root.appendChild(nomut);
            
            source = new DOMSource(d);
            result =  new StreamResult(output);
            transformer.transform(source,result);
            output.println();
            output.flush();
            risultato=input.readLine();
            if(risultato.equals("1"))
                testo.setText("utente non trovato,riprovare");
            else if (risultato.equals("2"))
                this.dispose();
        } catch (TransformerException | IOException | ParserConfigurationException ex) {
            Logger.getLogger(NuovaChat.class.getName()).log(Level.SEVERE, null, ex);
        }
            
                   
    }//GEN-LAST:event_InviaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Invia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeutente;
    private javax.swing.JTextArea testo;
    // End of variables declaration//GEN-END:variables
}
